### PR TITLE
Update stubs

### PR DESCRIPTION
**Pull request by samalexander**
Includes v5.11...v5.12

### CODE REVIEW

**Comment by szepeviktor** [comment]
Hello Sam! 👋 
Thank you for your work.
I suspect your commits are the outputs of stubs generator.
Have you seen these steps? https://github.com/php-stubs/acf-pro-stubs/blob/a79d5b7727895821c6d50f7e1acf3c7abc828b0d/generate.sh#L27-L43

**Comment by szepeviktor** [comment]
Also there is https://github.com/php-stubs/acf-pro-stubs/blob/master/release-latest-versions.sh

**Comment by samalexander** [comment]
I generated the commits using `release-latest-versions.sh`. Was that not the right way to do it?

**Comment by szepeviktor** [comment]
I see ` @param   n/a` which was supposed to to be fixed by `sed` above.

**Comment by szepeviktor** [comment]
And the first commit is huge!
https://github.com/php-stubs/acf-pro-stubs/pull/4/commits/9b2a935e9a7025416cf961a11dfae97e266ea833

**Comment by szepeviktor** [comment]
You made me wake up! :)

https://github.com/php-stubs/acf-pro-stubs/tags

**Comment by szepeviktor** [comment]
Thank you!

**Comment by samalexander** [comment]
Thanks @szepeviktor! Please could you tag the releases?

**Comment by samalexander** [comment]
Thanks @szepeviktor!

**Comment by samalexander** [comment]
Thanks @szepeviktor!

I can't update via composer, do you know why that might be?

**Comment by szepeviktor** [comment]
This is all I have.

```
$ composer require --dev php-stubs/acf-pro-stubs
Using version ^5.10 for php-stubs/acf-pro-stubs
./composer.json has been created
Running composer update php-stubs/acf-pro-stubs
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking php-stubs/acf-pro-stubs (v5.10.2)
  - Locking php-stubs/wordpress-stubs (v5.9.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing php-stubs/wordpress-stubs (v5.9.1): Extracting archive
  - Installing php-stubs/acf-pro-stubs (v5.10.2): Extracting archive
5 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
```

**Comment by samalexander** [comment]
Looks like it hasn't been crawled yet by Packagist, it only happens once a week. You could setup the [GitHub hook](https://packagist.org/about#how-to-update-packages) to push new versions immediately.

**Comment by szepeviktor** [comment]
This is a free package. One of my free packages. I do not have more resources. Sorry.
Please see https://packagist.org/packages/php-stubs/acf-pro-stubs

**Comment by szepeviktor** [comment]
@samalexander Would you like to add a README to this repo?

**Pull request closed without merging**
