### PR TITLE
Download ACF Pro release using Composer

### PR DESCRIPTION
**Pull request by juhojama**
Downloading ACF Pro release using directly via HTTP is obsolete (https://www.advancedcustomfields.com/resources/installing-acf-pro-with-composer/). This PR fixes this by using Composer to download ACF Pro release.

### CODE REVIEW

**Review by szepeviktor — APPROVED** [review]

**Comment by szepeviktor** [comment]
Could you verify this method by downloading/generating 6.2.7 again?

**Comment by juhojama** [comment]
Verified, the results are identical.

**Comment by szepeviktor** [comment]
Then it is release-time ✈️

**Comment by todeveni** [comment]
We're only interested in the stubs for development/phpstan/CI pipelines, but after 27fa6e4b7fc1a14c1b1ab790d689502f7d91e99c the stubs package have hard requirement of `wpengine/advanced-custom-fields-pro` package too.

```
  Problem 1
    - Root composer.json requires php-stubs/acf-pro-stubs ^6.3 -> satisfiable by php-stubs/acf-pro-stubs[v6.3.0, ..., v6.3.8].
    - php-stubs/acf-pro-stubs[v6.3.0, ..., v6.3.8] require wpengine/advanced-custom-fields-pro 6.3.8 -> could not be found in any version, there may be a typo in the package name.
```

**Comment by szepeviktor** [comment]
@todeveni Thank you for you report. It is spot on.

@juhojama Could you fix this?

**Comment by juhojama** [comment]
> We're only interested in the stubs for development/phpstan/CI pipelines, but after [27fa6e4](https://github.com/php-stubs/acf-pro-stubs/commit/27fa6e4b7fc1a14c1b1ab790d689502f7d91e99c) the stubs package have hard requirement of `wpengine/advanced-custom-fields-pro` package too.
> 
> ```
>   Problem 1
>     - Root composer.json requires php-stubs/acf-pro-stubs ^6.3 -> satisfiable by php-stubs/acf-pro-stubs[v6.3.0, ..., v6.3.8].
>     - php-stubs/acf-pro-stubs[v6.3.0, ..., v6.3.8] require wpengine/advanced-custom-fields-pro 6.3.8 -> could not be found in any version, there may be a typo in the package name.
> ```

Thanks for the heads up! Functional releases coming ASAP.

**Comment by szepeviktor** [comment]
Recent releases are **outside** the default branch ⚠️

**Comment by juhojama** [comment]
@szepeviktor @todeveni Please check if the latest release works for you https://github.com/php-stubs/acf-pro-stubs/releases/tag/v6.3.10

**Comment by szepeviktor** [comment]
@juhojama Red ALERT: published `auth.json`

# 🚨

Please get a new key.

**Comment by todeveni** [comment]
> @szepeviktor @todeveni Please check if the latest release works for you https://github.com/php-stubs/acf-pro-stubs/releases/tag/v6.3.10

Bumping acf-pro-stubs in composer.json from `^6.2` to `^6.3` and updating works now. Thanks.

```
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 4 updates, 0 removals
  - Upgrading php-stubs/acf-pro-stubs (v6.2.7 => v6.3.10)
 ```

**Pull request merged**
